### ISSUE TITLE
what is the grammar in your code doing? recognize mathematical expressions?any detail？

### ISSUE THREAD

**Issue by yogixRush** [deepakkarki/pyParsing#1]

**Comment by deepakkarki** [comment]
The very first line of my readme -

`pyParsing is a parsing toolkit which can parse strings of LL(1) grammars.`

The example is exactly parsing a mathematical expression. It should work for any LL(1) grammar you write, since this is a parser generator.

https://github.com/deepakkarki/pyParsing/blob/master/examples/main.py#L27
